# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-23 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181123_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_num',
            new_name='course_nums',
        ),
    ]
