# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-25 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181125_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learn_times',
            new_name='times',
        ),
    ]
